//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zavrsni
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentComment
    {
        public int IDcomment { get; set; }
        public int IDcontent { get; set; }
        public int IDuser { get; set; }
        public string Comment { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual User User { get; set; }
    }
}
