//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zavrsni
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public Content()
        {
            this.User = new HashSet<User>();
            this.ContentPage = new HashSet<ContentPage>();
            this.Location = new HashSet<Location>();
        }
    
        public int IDcontent { get; set; }
        public int IDcontentType { get; set; }
        public string Text { get; set; }
        public string URL { get; set; }
        public Nullable<int> IDeditor { get; set; }
        public Nullable<System.DateTime> TimeChanged { get; set; }
        public int IDauthor { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<User> User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ContentType ContentType { get; set; }
        public virtual ICollection<ContentPage> ContentPage { get; set; }
        public virtual ICollection<Location> Location { get; set; }
        public virtual User User2 { get; set; }
    }
}
