//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zavrsni
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.User1 = new HashSet<User>();
        }
    
        public int IDgroup { get; set; }
        public int IDgroupType { get; set; }
        public string Name { get; set; }
        public int IDgroupOwner { get; set; }
    
        public virtual User User { get; set; }
        public virtual GroupType GroupType { get; set; }
        public virtual ICollection<User> User1 { get; set; }
    }
}
