//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zavrsni
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Content = new HashSet<Content>();
            this.Page = new HashSet<Page>();
        }
    
        public int IDlocation { get; set; }
        public int IDcity { get; set; }
        public int IDlocationType { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
    
        public virtual City City { get; set; }
        public virtual LocationType LocationType { get; set; }
        public virtual ICollection<Content> Content { get; set; }
        public virtual ICollection<Page> Page { get; set; }
    }
}
