//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zavrsni
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationContent
    {
        public int IDlocation { get; set; }
        public int IDcontent { get; set; }
        public Nullable<System.DateTime> TimeChanged { get; set; }
    
        public virtual City City { get; set; }
        public virtual Content Content { get; set; }
        public virtual Location Location { get; set; }
    }
}
