//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zavrsni
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageReview
    {
        public int IDpage { get; set; }
        public int IDreviewer { get; set; }
        public short Mark { get; set; }
        public string ShortComment { get; set; }
    
        public virtual Page Page { get; set; }
        public virtual User User { get; set; }
    }
}
