//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zavrsni
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public Page()
        {
            this.ContentPage = new HashSet<ContentPage>();
            this.Contributor = new HashSet<Contributor>();
            this.PageReview = new HashSet<PageReview>();
            this.Tag = new HashSet<Tag>();
            this.Location = new HashSet<Location>();
        }
    
        public int IDpage { get; set; }
        public string name { get; set; }
        public int IDprivacy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int PageView { get; set; }
        public Nullable<int> IDeditor { get; set; }
        public Nullable<System.DateTime> TimeChanged { get; set; }
    
        public virtual ICollection<ContentPage> ContentPage { get; set; }
        public virtual ICollection<Contributor> Contributor { get; set; }
        public virtual ICollection<PageReview> PageReview { get; set; }
        public virtual User User { get; set; }
        public virtual Privacy Privacy { get; set; }
        public virtual ICollection<Tag> Tag { get; set; }
        public virtual ICollection<Location> Location { get; set; }
    }
}
