//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zavrsni
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel
    {
        public int IDpage { get; set; }
        public int IDlocation { get; set; }
        public string AlternateName { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Page Page { get; set; }
    }
}
