//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zavrsni
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZavrsniEFentities : DbContext
    {
        public ZavrsniEFentities()
            : base("name=ZavrsniEFentities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<Content> Content { get; set; }
        public virtual DbSet<ContentPage> ContentPage { get; set; }
        public virtual DbSet<ContentType> ContentType { get; set; }
        public virtual DbSet<Contributor> Contributor { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<GroupType> GroupType { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<LocationType> LocationType { get; set; }
        public virtual DbSet<Page> Page { get; set; }
        public virtual DbSet<PageReview> PageReview { get; set; }
        public virtual DbSet<Privacy> Privacy { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
